database:
  image: mysql:5.7
  container_name: database.dev
  command: mysqld --user=root --verbose
  ports:
    - "3308:3306"
  environment:
    MYSQL_DATABASE: "sakila"
    MYSQL_USER: "test"
    MYSQL_PASSWORD: "test"
    MYSQL_ROOT_PASSWORD: "root"
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"